[build]
  base    = "client"        # Points to the client directory
  publish = "client/build"  # Points to the build directory inside the client directory
  command = "npm run build" # The command to build your project
